<?php

/**
 * @file
 * Catalan Account activated template.
 *
 * @ingroup ces_message_template
 */

$subject = '[[exchange:shortname]] conpte activada';

$body = 'Benvingut [account:user:name],
 
Benvingut [exchange:name], your local exchange of the global Integral
Community Exchange System platform.

A continuació es presenten els detalls que necessita per accedir al seu compte 
en el [exchange:code] xarxa. 

Per arribar a la pàgina web vagi a [site:login-url]. Això el portarà a la
pàgina d\'inici de sessió.

Introduïu les dades següents:

Número de compte: [account:name]
Contrasenya: *

La interfície web està disponible en diversos idiomes . Si voleu seleccionar
un altre idioma , feu clic al seu nom a la cantonada superior dreta. en el seu
perfil personal només ha de seleccionar l\'idioma de la seva preferència.

Llegiu la <a href="http://www.integralces.net/doc/user">Guia de l\'usuari</a> per
esbrinar com funciona el lloc.

Després introduïu ofertes i interessos, vostè pot afegir tantes ofertes i interessos
addicionals com vulgui.

També pots pujar una fotografia de tu mateix perquè altres usuaris puguin veure\'t.

No dubti en posar-se en contacte amb qualsevol anunciant a \'Ofertes\' llista per a 
la compra de qualsevol bé i serveis oferts. 

Si us plau, no esperi que algú li compri a vostè abans que vostè utilitzi el sistema. 
Vostè no necessita tindrà crèdit abans de fer una compra, tindrà dèbit és part del 
sistema i simplement representa el seu compromís amb la comunitat.

feliç intercanvi!

[exchange:shortname] administrator:
[exchange:admin:fullname]
[exchange:admin:mail]
[exchange:admin:mainphone]
';
