<?php

function ces_user_menu(){
  $menu = array();
  $menu['ces'] = array(
    'title' => 'Welcome to Integral CES',
    'access callback' => TRUE,
    'page callback' => 'ces_user_main_page',
    'type' => MENU_CALLBACK,
  );
  $menu['ces/register'] = array(
    'title' => 'Register to Integral CES',
    'access callback' => TRUE,
    'page callback' => 'ces_user_register',
    'type' => MENU_CALLBACK,
  );
  return $menu;         
}

function ces_user_get_name($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $items = field_get_items('user', $account, 'ces_firstname');
  $userfullname = '';
  if(!empty($items)){
    $item = reset($items);
    $userfullname = $item['safe_value'] . ' ';
  }
  $items = field_get_items('user', $account, 'ces_surname');
  if(!empty($items)){
    $item = reset($items);
    $userfullname .= $item['safe_value'];
  }
  if(empty($userfullname)) {
    $userfullname = $account->name;
  }
  return $userfullname;
}

function ces_user_get_full_address($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $items = field_get_items('user', $account, 'ces_address');
  $address = '';
  if(!empty($items)){
    $item = reset($items);
    $address = $item['safe_value'] . ', ';
  }
  $items = field_get_items('user', $account, 'ces_postcode');
  if(!empty($items)){
    $item = reset($items);
    $address .= $item['safe_value'] . ', ';
  }
  $items = field_get_items('user', $account, 'ces_town');
  if(!empty($items)){
    $item = reset($items);
    $address .= $item['safe_value'] . ', ';
  }
  return $address;
}

function ces_user_get_main_phone($account = NULL) {
  if ($account == NULL) {
    global $user;
    $account = user_load($user->uid);
  }
  $order = array('ces_phonemobile', 'ces_phonework', 'ces_phonehome');
  foreach($order as $name) {
    $items = field_get_items('user', $account, $name);
    if(!empty($items)){
      $item = reset($items);
      return $item['safe_value'];
    }  
  }
  return '';
}
/**
 * Implements hook_form_alter().
 */
function ces_user_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'user_register_form' || $form_id == 'user_profile_form') {
    //Move all ces fields to account fieldset
    foreach ($form as $key => $field) {
      if(strlen($key)>4 && substr($key,0,4) == 'ces_') {
        $form['account'][$key] = $form[$key];
        unset($form[$key]);
      }
    }
    $form['account']['picture'] = $form['picture'];
    unset($form['picture']);
    //Set up weights
    $form['account']['name']['#weight'] = -10;
    $form['account']['current_pass']['#weight'] = -5;
    $form['account']['pass']['#weight'] = 0;
    $form['account']['status']['#weight'] = 60;
    $form['account']['roles']['#weight'] = 65;
  }else if($form_id == 'user_login_block') {
    //Override $form['links']
    $items = array();
    $items[] = l(t('Forgot password?'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
    $form['actions']['#weight'] = 90;
    $form['links'] = array(
      '#markup' => theme('item_list', array('items' => $items)),
      '#weight' => 100,
    );
    $form['end'] = array(
      '#markup' => '<div class="clearfix"></div>',
      '#weight' => 200,
    );
  }
}

function ces_user_user_view($account, $view_mode, $langcode) {
  //Set fields to be rendered with user profile item theme.
  $account->content['account'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'user-profile-account-items'
      )
    )
  );
  foreach($account->content as $key => $item) {
    if(substr($key,0,4) == 'ces_') {
      $account->content[$key]['#theme'] = 'user_profile_item';
      if(isset($account->content[$key][0])) {
        $account->content[$key]['#markup'] = $account->content[$key][0]['#markup'];
      }
      $account->content['account'][$key] = $account->content[$key];
      unset($account->content[$key]);
    }
  }
  $account->content['account']['ces_fullname'] = array(
    '#type' => 'markup',
    '#prefix' => '<h3 class="user-profile-ces-fullname">',
    '#suffix' => '</h3>',
    '#markup' => ces_user_get_name($account),
    'weight' => 0,
  );
  
  $account->content['account']['ces_fulladdress'] = array(
    '#theme' => 'user_profile_item',
    '#title' => t('Address'),
    '#markup' => ces_user_get_full_address($account),
    '#weight' => 15,
  );
  
  $account->content['account']['ces_email'] = array(
    '#theme' => 'user_profile_item',
    '#title' => t('Email'),
    '#markup' => $account->mail,
    '#weight' => 25,
  );
}
/**
 * Implements hook_block_info().
 */
function ces_user_block_info() {
  $block = array(
    'ces_user_register'=> array(
      'info' => t('CES register'),
      'cache' => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
    'ces_user_links' => array(
      'info' => t('CES front links'),
      'cache' => DRUPAL_CACHE_GLOBAL,
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => '<front>',
    ),
  );
  return $block;
}
/**
 * Implements hook_block_view().
 */
function ces_user_block_view($delta = '') {
  $block = array();
  $block['subject'] = '';
  if($delta == 'ces_user_register') {
    $content = array(
      'text' => array(
        '#type' => 'container',
        'p1' => array(
          '#markup' => t('New to Integal CES?'),
          '#prefix' => '<p><strong>',
          '#suffix' => '</strong></p>',
        ),
        'p2' => array(
          '#markup' => t('Find an exchange network near you and start trading using social money!'),
          '#prefix' => '<p>',
          '#suffix' => '</p>',
        ),
        'actions' => array(
          '#markup' => l('Register', 'ces/register'),
          '#prefix' => '<p>',
          '#suffix' => '</p>',
        ),
        '#attributes' => array(),
      )
    );
  } else if($delta == 'ces_user_links') {
    $content = array(
      '#theme' => 'item_list',
      '#attributes' => array('class' => array('front-links')),
      '#items' => array(
        l(t('Documentation'), 'http://www.integralces.net'),
        l(t('Developers'), 'http://drupal.org/sandbox/esteve/1367140'),
        l(t('Donate'), 'ces/donate'),
        l(t('New exchange'), 'ces/bank/exchange/new'),
        l(t('About'), 'ces/about'),
      ),
    );
  }
  $block['content'] = $content;
  return $block;
}
function ces_user_main_page(){
  global $user;
  //TODO: redirect to blog when is available.
  if($user->uid) drupal_goto('ces/bank/account/transaction');
  return array(
    'welcome' => array(
      '#prefix' => '<p class="front-welcome">',
      '#suffix' => '</p>',
      '#markup' => t('Welcome to <strong>Integral Community Exchange System</strong>,')
    ),
    'intro' => array(
      '#prefix' => '<p class="front-intro">',
      '#suffix' => '</p>',
      '#markup' => t('an open source platform featuring social currencies management for communities.')
    ),
    'features' => array(
      '#theme' => 'item_list',
      '#items' => array(
        'local' => t('Boost local economy, return it to human scale.'),
        'eco' => t('Help the environment, lower contamination.'),
        'speculation' => t('Gain the control over money, prevent speculation and abuse.'),
        'alternative' => t('Create a solid alternative to the current financial system.'),
        'community' => t('Empower your community. Have fun playing with social currency.')
      ),
      '#attributes' => array('class'=>array('front-list')),
    )
  );
}
function ces_user_register(){
  return 'Sorry! Not implemented yet!';
}