<?php
/**
 * @file
 * Implements the drupal hooks for this module.
 */

/**
 * Implements hook_theme
 */
function bank_theme(){
  return array(
   /* 'exchange_list' => array(
      'template' => 'exchange-list',
      'path' => drupal_get_path('module', 'bank'),
      'variables' => array('exchanges'=>NULL),
    ),
   */
  );
}

/**
 * Implements hook_menu()
 */
function bank_menu(){
  $menu = array();
  
  $menu['ces/bank/exchange/list'] = array(
    'title' => 'List exchanges',
    'description'=>'List of active exchanges',
    'page callback' => 'bank_exchange_list_page',
    'file'=>'bank.pages.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'access arguments' => array('view exchange'),
  );
  
  $menu['ces/bank/exchange/new'] = array(
    'title' => 'New exchange',
    'description' => 'Create a new exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_exchange_form', 3),
    'access arguments' => array('create exchange'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
  );
  
  $menu['ces/bank/exchange/view']   = array(
    'title' => 'View exchange',
    'description' => 'View exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_exchange_form',3,4),
    'access arguments' => array('view exchange'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type' => MENU_CALLBACK,
  );
  
  $menu['ces/bank/exchange/edit']   = array(
    'title' => 'Edit exchange',
    'description' => 'Edit exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_exchange_form',3,4),
    'access arguments' => array('edit exchange'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type' => MENU_CALLBACK,
  );

  $menu['ces/bank/account/new'] = array(
    'title' => 'New Account',
    'description' => 'Create a new banking account.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_account_form', 3, 4),
    'access arguments' => array('create account'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type'=> MENU_CALLBACK,
  );
  
  $menu['ces/bank/account/edit'] = array(
    'title' => 'Edit Account',
    'description' => 'Edit a banking account.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_account_form', 3, 4),
    'access arguments' => array('edit account'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type'=> MENU_CALLBACK,
  );
  
  $menu['ces/bank/account/view'] = array(
    'title' => 'View Account',
    'description' => 'View banking account properties.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_account_form', 3, 4),
    'access arguments' => array('view account'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type'=> MENU_CALLBACK,
  );
  
  $menu['ces/bank/account/list'] = array(
    'title' => 'List accounts' ,
    'description' => 'List and info of user banking accounts',
    'page callback' => 'bank_account_list_page',
    'file' => 'bank.pages.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'access arguments' => array('view account'),
  );
  
  $menu['ces/bank/transaction'] = array(
    'title' => 'Enter single transaction',
    'description' => 'Enter single transaction your account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bank_transaction_form', 3, 4),
    'access arguments' => array('create transaction'),
    'file' => 'bank.forms.inc',
    'file path' => drupal_get_path('module', 'bank'),
    'type'=> MENU_CALLBACK,
  );
  
  return $menu;
}


/**
 * Implements hook_account_limit_classes()
 */
function bank_account_limit_classes(){
  return array('AbsoluteCreditLimit', 'AbsoluteDebitLimit');
}

/**
 * Implements hook_decorated_transaction_classes()
 */
function bank_decorated_transaction_classes(){
  return array('InterExchangeTransaction', 'LevyedTransaction');
}

function bank_ces_notify_messages($key, $langcode){
  $a = array();
  $b = array('langcode' => $langcode);
  switch ($key){
    case 'new exchange': 
      return array(
        'subject' => t('New Exchange [exchange:code] - [exchange:shortname] request',$a,$b),
        'body' => t('A new exchange has been registered.

Visit the CES administrative interface at [url:absolute]/admin/ces to activate or discard it. See some details below:

Code: [exchange:code]
Short name: [exchange:shortname]
Full name: [exchange:name]  
Country: [exchange:country]
Location: [exchange:town] ([exchange:region])
Web site: [exchange:website]
Currency: [exchange:currencysymbol] ( [exchange:currencyname] ), value [exchange:currencyvalue]
User: [exchange:admin:name] <[exchange:admin:mail]>

', $a, $b)
      );
    case 'new account': 
      return array(
        'subject' => t('New account request for [exchange:code] - [exchange:shortname]',$a,$b),
        'body' => t('Another account request for [exchange:name]. Go to the administrative interface at [url:absolute]/ces/bank/exchange/admin to activate or discard it.

See registration details below:

Exchange: [exchange:code]
Account name: [account:name]
Account type: [account:kind]
User: [account:user]', $a, $b)
      );
    case 'account debited':
      return array(
        'subject' => t('Your account has been debited'),
        'body' => t('Your account [account:name] has been debited.

...', $a, $b),
      );
    case 'account credited':
      return array(
        'subject' => t('Your account has been credited'),
        'body' => t('Your account [account:name] has been credited.

...', $a, $b),
      );
  }
  return FALSE;
}


