<?php
/**
 * @file
 * Implements the drupal hooks for this module.
 */
/**
 * Implements hook_mail().
 */
function ces_notify_mail($key, &$message, $params) {
  list($module, $name) = explode(' ', $key, 2);
  $record = array(
    'module' => $module,
    'name' => $name,
  );
  if (isset($message['language']) && !empty($message['language'])) {
    $record['lang'] = $message['language']->langcode;
  }
  if (isset($message['from']) && (($sender = user_load_by_mail($message['from']))!==FALSE)) {
    $record['sender'] = $sender->uid;
  }
  if (isset($message['to']) && (($recipient = user_load_by_mail($message['to']))!==FALSE)) {
    $record['recipient'] = $recipient->uid;
  }

  $notifier = new Notifier();
  $notifier->getMessageTemplate($record);

  $message['subject'] .= token_replace($record['subject'], $params);
  $message['body'][] = token_replace($record['body'], $params);
}