<?php
/**
 * @file
 * Implements the drupal hooks for this module.
 */

/**
 * Implements hook_menu().
 */
function ces_import4ces_menu() {
  $menu['ces/admin/import4ces'] = array(
    'title' => 'Import from CES',
    'decription' => 'Import data from CES',
    'page callback' => 'ces_import4ces_run_script',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'exchange', CES_CURRENT_EXCHANGE),
  );
  return $menu;
}
/**
 * Run the given script.
 */
function ces_import4ces_run_script() {
  $path = drupal_get_path('module', 'ces_import4ces');
  ob_start();
  include $path . '/ces_import4ces.php';
  $output = ob_get_clean();
  return $output;
}
