<?php
/**
 * @file
 * Implements the drupal hooks for this module.
 */

/**
 * Implements hook_theme().
 */
function ces_bank_theme() {
  return array(
    'ces_bank_exchange_view' => array(
      'render element' => 'element',
      'path' => drupal_get_path('module', 'ces_bank'),
      'file' => 'ces_bank.theme.inc',
    ),
    'ces_bank_account_view' => array(
      'render element' => 'element',
      'path' => drupal_get_path('module', 'ces_bank'),
      'file' => 'ces_bank.theme.inc',
    )
  );
}

function ces_bank_access($permission, $object, $objectid, $account = NULL) {
  global $user;
  if ($account == NULL) {
    $account = $user->uid;
  }
  $bank = new Bank();
  return $bank->access($permission, $object, $objectid, $account);
}

/**
 * Implements hook_menu().
 */
function ces_bank_menu() {
  $menu = array();
  //DASHBOARD
  $menu['ces/bank/dashboard'] = array(
    'title' => 'Dashboard' ,
    'description' => 'User dashboard',
    'page callback' => 'ces_bank_account_list_page',
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['ces/bank/admin'] = array(
    'title' => 'Administer CES bank',
    'description' => 'Top administer interface for CES Bank',
    'page callback' => 'ces_bank_admin_page',
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'global', 0),
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['ces/bank/exchange'] = array(
    'title' => 'List exchanges',
    'description' => 'List of active exchanges',
    'page callback' => 'ces_bank_exchange_list_page',
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'global statistics', 0),
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['ces/bank/exchange/new'] = array(
    'title' => 'New exchange',
    'description' => 'Create a new exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_exchange_form', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'global exchangecreator', 0),
    'type' => MENU_LOCAL_ACTION,
  );
  $menu['ces/bank/exchange/%'] = array(
    'title' => 'View exchange',
    'description' => 'View exchange',
    'page callback' => 'ces_bank_exchange_view',
    'page arguments' => array(3),
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'exchange details', 3),
  );
  $menu['ces/bank/exchange/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['ces/bank/exchange/%/activate'] = array(
    'title' => 'Activate exchange',
    'description' => 'Activate exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_exchange_form', 'activate', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'global exchangeactivator', 0),
  );
  $menu['ces/bank/exchange/%/edit'] = array(
    'title' => 'Edit exchange',
    'description' => 'Edit exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_exchange_form', 'edit', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('edit', 'exchange', 3),
  );
  $menu['ces/bank/exchange/%/admin'] = array(
    'title' => 'Administer exchange',
    'description' => 'Exchange administrative interface',
    'page callback' => 'ces_bank_exchange_admin',
    'page arguments' => array(3),
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'exchange', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/delete'] = array(
    'title' => 'Delete exchange',
    'description' => 'Delete exchange',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_exchange_form', 'delete', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'exchange', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/account'] = array(
    'title' => 'Exchange accounts',
    'description' => 'Exchange accounts list',
    'page callback' => 'ces_bank_exchange_accounts_page',
    'page arguments' => array(3),
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'exchange accounts', 3),
  );
  $menu['ces/bank/exchange/%/account/new'] = array(
    'title' => 'New account',
    'description' => 'Create a new account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_account_form', 'new', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'exchange accountcreator', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/account/%'] = array(
    'title' => 'View',
    'description' => 'View account details',
    'page callback' => 'ces_bank_account_view',
    'page arguments' => array(5),
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'account details', 5),
  );
  $menu['ces/bank/exchange/%/account/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['ces/bank/exchange/%/account/%/edit'] = array(
    'title' => 'Edit account',
    'description' => 'Edit account details',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_account_form', 'edit', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('edit', 'account', 5),
  );
  $menu['ces/bank/exchange/%/account/%/activate'] = array(
    'title' => 'Activate account',
    'description' => 'Activate account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_account_form', 'activate', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'exchange accountactivator', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/account/%/delete'] = array(
    'title' => 'Delete',
    'description' => 'Delete account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_account_form', 'delete', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'account', 5),
  );
  $menu['ces/bank/exchange/%/account/%/transaction'] = array(
    'title' => 'Account statement' ,
    'description' => 'Last transactions with this account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_account_statement_form', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'account transactions', 5),
  );
  $menu['ces/bank/exchange/%/account/%/transaction/sell'] = array(
    'title' => 'Charge a sale',
    'description' => 'Create a transaction in order to charge a sale',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_transaction_form', 'new', 3, 5, NULL),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'account seller', 5),
  );
  $menu['ces/bank/exchange/%/account/%/transaction/buy'] = array(
    'title' => 'Pay for a purchase',
    'description' => 'Create a transaction in order to pay for a purchase',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_transaction_form', 'new', 3, NULL, 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'account buyer', 5),
  );
  $menu['ces/bank/exchange/%/transaction'] = array(
    'title' => 'Exchange transactions',
    'description' => 'View exchange transactions list',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_exchange_statement_form', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'exchange transactions', 3),
  );
  $menu['ces/bank/exchange/%/transaction/new'] = array(
    'title' => 'Create transaction',
    'description' => 'Create a transaction between two accounts',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_transaction_form', 'new'),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'exchange transactioncreator', 3),
  );
  $menu['ces/bank/exchange/%/transaction/%'] = array(
    'title' => 'View transaction',
    'description' => 'View transaction details',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_transaction_form', 'view', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'transaction details', 5),
  );
  $menu['ces/bank/exchange/%/transaction/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['ces/bank/exchange/%/transaction/%/trigger'] = array(
    'title' => 'Apply transaction',
    'description' => 'Apply transaction',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_transaction_confirm_form', 'trigger', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_CALLBACK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('use', 'transaction', 5),
  );
  $menu['ces/bank/exchange/%/limitchain'] = array(
    'title' => 'Exchange limit chains',
    'description' => 'Exchange limit chain list',
    'page callback' => 'ces_bank_limitchain_list_page',
    'page arguments' => array(3),
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'exchange limitchains', 3),
  );
  $menu['ces/bank/exchange/%/limitchain/new'] = array(
    'title' => 'New limit chain',
    'description' => 'Create a new limit chain',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_limitchain_form', 'new', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'exchange', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/limitchain/%'] = array(
    'title' => 'View limit chain',
    'description' => 'View limit chain details',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_limitchain_form', 'view', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('view', 'exchange limitchains', 3),
  );
  $menu['ces/bank/exchange/%/limitchain/%/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $menu['ces/bank/exchange/%/limitchain/%/edit'] = array(
    'title' => 'Edit limit chain',
    'description' => 'Edit a limit chain',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_limitchain_form', 'edit', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('edit', 'exchange', 3),
  );
  //TODO
  $menu['ces/bank/exchange/%/limitchain/%/delete'] = array(
    'title' => 'Delete limit chain',
    'description' => 'Delete a limit chain',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_limitchain_form', 'delete', 5),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('admin', 'exchange', 3),
  );
  $menu['ces/bank/permission'] = array(
    'title' => 'Permissions',
    'description' => 'Adminiser permissions',
    'page callback' => 'ces_bank_permissions_page',
    'file' => 'ces_bank.pages.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $menu['ces/bank/permission/new'] = array(
    'title' => 'New',
    'description' => 'New permission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_permission_form', 'new'),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_ACTION,
    'access callback' => TRUE,
  );
  $menu['ces/bank/permission/%/edit'] = array(
    'title' => 'Edit permission',
    'description' => 'Edit permission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ces_bank_permission_form', 'edit', 3),
    'file' => 'ces_bank.forms.inc',
    'file path' => drupal_get_path('module', 'ces_bank'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'ces_bank_access',
    'access arguments' => array('edit', 'permission', 3),
  );
  foreach ($menu as $key => $value) {
    $menu[$key]['menu_name'] = 'ces';
  }
  return $menu;
}

/**
 * Implements hook_account_limit_classes().
 */
function ces_bank_account_limit_classes() {
  return array('AbsoluteCreditLimit', 'AbsoluteDebitLimit');
}

/**
 * Implements hook_decorated_transaction_classes().
 */
function ces_bank_decorated_transaction_classes() {
  return array('InterExchangeTransaction', 'LevyedTransaction');
}
/**
 * Implements hook_block_info().
 */
function ces_bank_block_info() {
  $block = array();
  $block['navigation']['info'] = t('CES bank navigation');
  $block['navigation']['cache'] = DRUPAL_CACHE_PER_USER;

  return $block;
}
/**
 * Implements hook_block_view().
 */
function ces_bank_block_view() {
  global $user;
  $bank = new Bank();
  $tree = array();
  $tree[] = _ces_bank_get_link_item('ces/bank/dashboard', t('Dashboard'));
  $tree[] = _ces_bank_get_link_item('ces/bank/exchange', t('All exchanges'));
  $tree[] = _ces_bank_get_link_item('ces/bank/permission', t('Permissions'));
  $exchanges = array();
  $accounts = array();
  //Compute relevant exchanges and accounts from permissions.
  $perms = $bank->getAdministrablePermissions($user->uid);
  foreach ($perms as $perm) {
    if ($perm['scope']!='global') { //discard global permissions.
      if (substr($perm['object'], 0, strlen('exchange')) == 'exchange') {
        if (!isset($exchanges[$perm['objectid']])) {
          $exchanges[$perm['objectid']] = $bank->getExchange($perm['objectid']);
        }
      }
      if (substr($perm['object'], 0, strlen('account')) == 'account') {
        if (!isset($accounts[$perm['objectid']])) {
          $accounts[$perm['objectid']] = $bank->getAccount($perm['objectid']);
        }
      }
    }
  }
  //Add account exchanges.
  foreach ($accounts as $account) {
    if (!isset($exchanges[$account['exchange']])) {
      $exchanges[$account['exchange']] = $bank->getExchange($account['exchange']);
    }
  }
  //Build exchange-related menu.
  foreach ($exchanges as $exchange) {
    $exhref = 'ces/bank/exchange/' . $exchange['id'];
    $exchilds = array();
    foreach ($accounts as $account) {
      if ($account['exchange'] == $exchange['id']) {
        $achref = $exhref . '/account/' . $account['id'];
        $acchilds = array();
        $acchilds[] = _ces_bank_get_link_item($achref . '/transaction', t('Statement'));
        $acchilds[] = _ces_bank_get_link_item($achref . '/transaction/sell', t('Charge a sale'));
        $acchilds[] = _ces_bank_get_link_item($achref . '/transaction/buy', t('Pay for a purchase'));
        $aclink = _ces_bank_get_link_item($achref, $account['name'], $acchilds);
        $exchilds[] = $aclink;
      }
    }
    if (ces_bank_access('admin', 'exchange', $exchange['id'])) {
      $exchilds[] = _ces_bank_get_link_item($exhref . '/admin', t('Administrative interface'));
    }
    $exlink = _ces_bank_get_link_item($exhref, $exchange['shortname'], $exchilds);
    $tree[] = $exlink;
  }
  $block = array(
    'subject' => t('CES Navigation'),
    'content' => menu_tree_output($tree),
  );
  return $block;
}
function _ces_bank_get_link_item($href, $title, $childs = array()) {
  static $counter = 0;
  $path = $_GET['q'];
  $link = array(
    'link' => array(
      'access' => TRUE,
      'hidden' => FALSE,
      'has_children' => !empty($childs),
      'in_active_trail' => (strpos($path, $href)!=-1),
      'localized_options' => array(
        'attributes' => array(
          'class' => array(),
        ),
      ),
      'href' => $href,
      'menu_name' => 'ces',
      'title' => $title,
      'mlid' => $counter++,
    ),
    'below' => $childs,
  );
  return $link;
}
/**
 * Implements hook_token_info().
 */
function ces_bank_token_info() {
  return array(
    'types' => array(
      'exchange' => array(
        'name' => t('Exchange'),
        'description' => t('Tokens for bank exchanges.'),
      ),
      'account' => array(
        'name'  => t('Account'),
        'description' => t('Tokens for bank accounts.')
      ),
      'transaction' => array(
        'name' => t('Transaction'),
        'description' => t('Tokens for bank transactions.')
      )
    ),
    'tokens' => array(
      'exchange' => array(
        'code' => array(
          'name'   => t('Exchange code'),
          'description' => t('The 4 letter exchange code.'),
        ),
        'shortname' => array(
          'name' => t('Exchange short name'),
          'description' => t('Exchange short name.'),
        ),
        'name' => array(
          'name' => t('Exchange full name'),
          'description' => t('Exchange full name.'),
        ),
        'country' => array(
          'name' => t('Exchange country'),
          'description' => t('Exchange country.'),
        ),
        'town' => array(
          'name' => t('Exchange town'),
          'description' => t('Exchange town.'),
        ),
        'region' => array(
          'name'   => t('Exchange region'),
          'description' => t('Exchange region within the country.'),
        ),
        'website' => array(
          'name' => t('Exchange website'),
          'description' => t('Exchange website.'),
        ),
        'currencysymbol' => array(
          'name' => t('Currency symbol'),
          'description' => t('Exchange currency symbol.'),
        ),
        'currencyname' => array(
          'name'   => t('Currency name'),
          'description' => t('Exchange currency name.'),
        ),
        'currenciesname' => array(
          'name'   => t('Currency name plural'),
          'description' => t('Exchange currency name in plural.'),
        ),
        'currencyvalue' => array(
          'name'   => t('Currency value'),
          'description' => t('Exchange currency value in hours of work.'),
        ),
        'admin' => array(
          'name'   => t('Exchange administrator'),
          'description' => t('Exchange administrator user.'),
          'type' => 'user',
        )
      ),
      'account' => array(
        'name' => array(
          'name' => t('Account identifier'),
          'description' => t('4 letter exchange identifier plus 4 number account code.'),
        ),
        'kind' => array(
          'name' => t('Type'),
          'description' => t('Account type.'),
        ),
        'user' => array(
          'name' => t('Account user'),
          'description' => t('Account user.'),
          'type' => 'user',
        )
      ),
      'transaction' => array(
        'fromaccount' => array(
          'name' => t('Buyer account'),
          'description' => t('The buyer account object.'),
          'type' => 'account',
        ),
        'toaccount' => array(
          'name' => t('Seller account'),
          'description' => t('The seller account object.'),
          'type' => 'account',
        ),
        'amount' => array(
          'name' => t('Amount'),
          'description' => t('The transaction amount.'),
        ),
        'concept' => array(
          'name' => t('Description'),
          'description' => t('The concept of the transaction.')
        ),
      ),
    ),
  );
}

/**
 * Implements hook_tokens().
 */
function ces_bank_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);

  if ($type == 'exchange' && !empty($data['exchange'])) {
    $exchange = $data['exchange'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'code':
          $replacements[$original] = $sanitize?check_plain($exchange['code']):$exchange['code'];
          break;
        case 'shortname':
          $replacements[$original] = $sanitize?check_plain($exchange['shortname']):$exchange['shortname'];
          break;
        case 'name':
          $replacements[$original] = $sanitize?check_plain($exchange['name']):$exchange['name'];
          break;
        case 'country':
          $replacements[$original] = $sanitize?check_plain($exchange['country']):$exchange['country'];
          break;
        case 'town':
          $replacements[$original] = $sanitize?check_plain($exchange['town']):$exchange['town'];
          break;
        case 'region':
          $replacements[$original] = $sanitize?check_plain($exchange['region']):$exchange['region'];
          break;
        case 'website':
          $replacements[$original] = $sanitize?check_plain($exchange['website']):$exchange['website'];
          break;
        case 'currencysymbol':
          $replacements[$original] = $sanitize?check_plain($exchange['currencysymbol']):$exchange['currencysymbol'];
          break;
        case 'currencyname':
          $replacements[$original] = $sanitize?check_plain($exchange['currencyname']):$exchange['currencyname'];
          break;
        case 'currenciesname':
          $replacements[$original] = $sanitize?check_plain($exchange['currenciesname']):$exchange['currenciesname'];
          break;
        case 'currencyvalue':
          $replacements[$original] = $sanitize?check_plain($exchange['currencyvalue']):$exchange['currencyvalue'];
          break;
      }
    }
    if ($admin_tokens = token_find_with_prefix($tokens, 'admin')) {
      $replacements += token_generate('user', $admin_tokens, array('user' => user_load($exchange['admin'])), $options);
    }
  }
  if ($type == 'account' && !empty($data['account'])) {
    $account = $data['account'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'name':
          $replacements[$original] = $sanitize?check_plain($account['name']):$account['name'];
          break;
        case 'kind':
          $replacements[$original] = $sanitize?check_plain($account['kind']):$account['kind'];
          break;
      }
    }
    if ($user_tokens = token_find_with_prefix($tokens, 'user')) {
      $accountUser = reset($account['users']);
      $uid = $accountUser['user'];
      $replacements += token_generate('user', $user_tokens, array('user' => user_load($uid)), $options);
    }
  }
  if ($type == 'transaction' && !empty($data['transaction'])) {
    $transaction = $data['transaction'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'amount':
          $replacements[$original] = $sanitize?check_plain($transaction['amount']):$transaction['amount'];
          break;
        case 'concept':
          $replacements[$original] = $sanitize?check_plain($transaction['concept']):$transaction['concept'];
          break;
      }
      if ($fromaccount_tokens = token_find_with_prefix($tokens, 'fromaccount')) {
        $bank = new Bank();
        $replacements += token_generate('account', $fromaccount_tokens, array('account' => $bank->getAccountByName($transaction['fromaccount'])), $options);
      }
      if ($toaccount_tokens = token_find_with_prefix($tokens, 'toaccount')) {
        $bank = new Bank();
        $replacements += token_generate('account', $toaccount_tokens, array('account' => $bank->getAccountByName($transaction['toaccount'])), $options);
      }
    }
  }
  return $replacements;
}
/**
 * Implements ces_motify_messages().
 */
function ces_bank_ces_notify_messages($key, $langcode) {
  $a = array();
  $b = array('langcode' => $langcode);
  switch ($key) {
    case 'new exchange':
      return array(
        'subject' => t('New Exchange [exchange:code] - [exchange:shortname] request', $a, $b),
        'body' => t('A new exchange has been registered.

Visit the CES administrative interface at [url:absolute]/admin/ces to activate or discard it. See some details below:

Code: [exchange:code]
Short name: [exchange:shortname]
Full name: [exchange:name]
Country: [exchange:country]
Location: [exchange:town] ([exchange:region])
Web site: [exchange:website]
Currency: [exchange:currencysymbol] ( [exchange:currencyname] ), value [exchange:currencyvalue]
User: [exchange:admin:name] <[exchange:admin:mail]>

', $a, $b)
      );
    case 'exchange activated':
      return array(
          'subject' => t('Exchange [exchange:code] activated', $a, $b),
          'body' => t('Your new exchange request has been activated. bla bla bla', $a, $b),
      );
    case 'new account':
      return array(
        'subject' => t('New account request for [exchange:code] - [exchange:shortname]', $a, $b),
        'body' => t('Another account request for [exchange:name]. Go to the administrative interface at [url:absolute]/ces/bank/exchange/admin to activate or discard it.

See registration details below:

Exchange: [exchange:code]
Account name: [account:name]
Account type: [account:kind]
User: [account:user:name]', $a, $b)
      );
    case 'account activated':
      return array(
        'subject' => t('Account activated'),
        'body' => t('Your account [account:name] has been activated. You can now start using it and bla bla bla',
                $a , $b)
      );
    case 'account debited':
      return array(
        'subject' => t('Your account has been debited'),
        'body' => t(
'[transaction:fromaccount:exchange:name]: Your account [transaction:fromaccount:name] has been debited.

See transaction details below:

Seller account: [transaction:toaccount:name]
Seller name: [transaction:toaccount:user:name] <[transaction:toaccount:user:mail]>
Description: [transaction:concept]
Amount: [transaction:amount][transaction:fromaccount:exchange:currencysymbol]
Ordered by: [transaction:user:name] <[transaction:user:mail]>

If you were satisfied with this purchase please <a href="">leave a recommendation</a> for the seller.

View your current <a href="">statement of account</a>.

If this debit is incorrect contact the seller within 10 days to have it corrected.

', $a, $b),
      );
    case 'account credited':
      return array(
        'subject' => t('Your account [transaction:toaccount:name] has been credited'),
        'body' => t('[transaction:toaccount:exchange:name]:Your account [transaction:toaccount:name] has been credited.

See transaction details below:

Buyer account: [transaction:fromaccount:name]
Buyer name: [transaction:fromaccount:user:name] <[transaction:fromaccount:user:mail]>
Description: [transaction:concept]
Amount: [transaction:amount][transaction:toaccount:exchange:currencysymbol]
Ordered by: [transaction:user:name] <[transaction:user:mail]>

', $a, $b),
      );
  }
  return FALSE;
}